### ISSUE TITLE
Get-SyncConnections.ps1 error

### ISSUE THREAD

**Issue by florysedelacaze** [bkuppens/powershell#2]
Hi ! Thanks for this script.  I know you posted it two years ago but could you help me please ?

I have an issue when I run ".\Get-SyncConnections.ps1 -OutputFile c:\temp\SyncConnections.xml"

At C:\Scripts\UPS\Get-SyncConnections.ps1:20 char:1
+ [CmdletBinding()]
+ ~~~~~~~~~~~~~~~~~
Unexpected attribute 'CmdletBinding'.
At C:\Scripts\UPS\Get-SyncConnections.ps1:21 char:1
+ param(
+ ~~~~~
Unexpected token 'param' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedAttribute

Thanks in advance,
Regards

**Comment by bkuppens** [comment]
That error is mostly due to a copy/paste error of the script. The "<#" en "#>" markers are important for the comments section. Can you verify if these are in place? If they are and it's still not working, can you send me a copy of the script you are trying to execute (you can send it to bart.kuppens@outlook.com).
